import { Component } from '@angular/core';

@Component({
  selector: 'app-landing-course-card',
  templateUrl: './landing-course-card.component.html',
  styleUrls: ['./landing-course-card.component.scss'],
})
export class LandingCourseCardComponent {
  courses = [
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: '../../../assets/svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: '../../../assets/svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
  ];
  
}
